config/routes.rb
Sputnik::Application.routes.draw do
  scope '(:locale)', locale: /en|ru/ do
    root :to => 'index#show_lists', as: 'show_lists'
    match 'activity_list/:id' => 'index#show_list', as: 'show_list'

    match 'activities' => 'index#show_activities', as: 'show_activities'
    match 'activity/:id' => 'index#show_activity', as: 'show_activity'
  end

  match '/admin' => 'admin#index', as: 'admin'
  scope '/admin' do
    resources :lists, :activities, :activity_photos
  end

end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  lead_text  :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  photo      :string(255)
#

class List < ActiveRecord::Base
  attr_accessor :activities_params
  
  has_and_belongs_to_many :activities

  attr_accessible :title, :lead_text, :photo, :translations_attributes, :activities_params
  is_uploadcare_file :photo

  translates :title, :lead_text
  accepts_nested_attributes_for :translations
end

app/controllers/lists_controller.rb
class ListsController < AdminController
  before_filter :get_activities, only: [:new, :edit]
  after_filter :save_activities, only: [:create, :update]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: t('.list_created') }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: t('.activity_updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

private

  def get_activities
    @activities = Activity.all.map {|activity| [activity.title, activity.id]}
  end

  def save_activities
    if params[:list][:activities_params]
      list = List.find(params[:id])

      params[:list][:activities_params].each do |act_param|
        activity = Activity.find(act_param[1][:id])
        list.activities << activity if !list.activities.include?(activity)
        if act_param[1][:_destroy] && act_param[1][:_destroy] == "1"
          list.activities.destroy(activity)
        end
      end
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for @list, html: { class: 'form' } do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="col-md-6">
    <div class="field form-group">
      <%= f.label 'Название (english)' %><br />
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="col-md-6">
    <%= f.globalize_fields_for :ru do |f_ru| %>
    <div class="field form-group">
      <%= f_ru.label 'Название (русский)' %><br />
      <%= f_ru.text_field :title, class: 'form-control' %>
      </div>
    <% end %>
  </div>

  <div class="col-md-6">
    <div class="field form-group">
      <%= f.label 'Описание (english)' %><br />
      <%= f.text_area :lead_text, class: 'form-control' %>
    </div>
  </div>

  <div class="col-md-6">
    <%= f.globalize_fields_for :ru do |f_ru| %>
    <div class="field form-group">
      <%= f_ru.label 'Описание (русский)' %><br />
      <%= f_ru.text_area :lead_text, class: 'form-control' %>
    </div>
    <% end %>
  </div>

  <div class="col-md-12">
    <div class="field form-group">
      <%= f.label 'Обложка' %><br />
      <%= f.uploadcare_uploader_field :photo %>
    </div>
  </div>

  <div class="col-md-12">
    <div class="field form-group activities">
      <%= f.label 'Экскурсии' %><br />

      <div class="activities-box">
        <% if @list.activities.present? %>
          <% for activity in @list.activities %>
            <%= fields_for 'list[activities_params][]', activity do |ff| %>
              <div class="activity-box">
                <h4><%= link_to ff.object.title, activity_path(ff.object) %> 
                    <%= link_to 'Удалить из списка', '#', class: 'btn btn-warning btn-xs btn-remove' %></h4>
                <%= ff.hidden_field :_destroy, class: "destroy" %>
                <%= ff.hidden_field :id %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <%= link_to 'Добавить экскурсию', '#', 
                                       remote: true, 
                                       class: 'add-activity-link btn btn-primary btn-xs', 
                                       data: { partial: render('add_to_list', f: f).gsub('\n','') } %>
    </div>
  </div>

  <div class="col-md-12">
    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Редактировать список экскурсий</h1>

<%= render 'form' %>

<div class="col-md-12">
    <br>
    <%= link_to 'Показать', @list %> |
    <%= link_to 'Назад', lists_path %>
</div>

app/views/lists/index.html.erb
<h1>Cписок экскурсий</h1>

<table class="table">
  <tr>
    <th>Название</th>
    <th>Описание</th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= link_to list.title, list %></td>
    <td><%= list.lead_text %></td>
    <td><%= link_to 'Редактировать', edit_list_path(list) %></td>
    <td><%= link_to 'Удалить', list, confirm: 'Точно удалить?', method: :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Новый список экскурсий', new_list_path, class: 'btn btn-primary' %>

app/views/lists/new.html.erb
<h1>Новый список экскурсий</h1>

<%= render 'form' %>

<div class="col-md-12">
    <br>
    <%= link_to 'Назад', lists_path %>
</div>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Название:</b>
  <div><%= @list.title %></div>
</p>

<p>
  <b>Описание:</b>
  <div><%= @list.lead_text %></div>
</p>

<p>
  <b>Обложка:</b>
  <div><%= image_tag @list.photo.public_url %></div>
</p>


<%= link_to 'Редактировать список', edit_list_path(@list) %> |
<%= link_to 'Назад', lists_path %>