config/routes.rb
Sputnik::Application.routes.draw do
  scope '(:locale)', locale: /en|ru/ do
    root :to => 'index#show_lists', as: 'show_lists'
    match 'activity_list/:id' => 'index#show_list', as: 'show_list'

    match 'activities' => 'index#show_activities', as: 'show_activities'
    match 'activity/:id' => 'index#show_activity', as: 'show_activity'
  end

  match '/admin' => 'admin#index', as: 'admin'
  scope '/admin' do
    resources :lists, :activities, :activity_photos
  end

end

app/models/activity_photo.rb
# == Schema Information
#
# Table name: activity_photos
#
#  id          :integer          not null, primary key
#  file        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  title       :string(255)
#  activity_id :integer
#  is_main     :boolean
#

class ActivityPhoto < ActiveRecord::Base
  belongs_to :activity

  attr_accessible :title, :file, :activity_id, :is_main
  is_uploadcare_file :file

  translates :title
end

app/controllers/activity_photos_controller.rb
class ActivityPhotosController < AdminController
  before_filter :get_activities, only: [:new, :edit]

  # GET /activity_photos
  # GET /activity_photos.json
  def index
    @activity_photos = ActivityPhoto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activity_photos }
    end
  end

  # GET /activity_photos/1
  # GET /activity_photos/1.json
  def show
    @activity_photo = ActivityPhoto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity_photo }
    end
  end

  # GET /activity_photos/new
  # GET /activity_photos/new.json
  def new
    @activity_photo = ActivityPhoto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity_photo }
    end
  end

  # GET /activity_photos/1/edit
  def edit
    @activity_photo = ActivityPhoto.find(params[:id])
  end

  # POST /activity_photos
  # POST /activity_photos.json
  def create
    @activity_photo = ActivityPhoto.new(params[:activity_photo])

    respond_to do |format|
      if @activity_photo.save
        format.html { redirect_to @activity_photo, notice: 'Activity photo was successfully created.' }
        format.json { render json: @activity_photo, status: :created, location: @activity_photo }
      else
        format.html { render action: "new" }
        format.json { render json: @activity_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activity_photos/1
  # PUT /activity_photos/1.json
  def update
    @activity_photo = ActivityPhoto.find(params[:id])

    respond_to do |format|
      if @activity_photo.update_attributes(params[:activity_photo])
        format.html { redirect_to @activity_photo, notice: 'Activity photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_photos/1
  # DELETE /activity_photos/1.json
  def destroy
    @activity_photo = ActivityPhoto.find(params[:id])
    @activity_photo.destroy

    respond_to do |format|
      format.html { redirect_to activity_photos_url }
      format.json { head :no_content }
    end
  end

private

  def get_activities
    @activities = Activity.all.map {|act| [act.lead_text[0..15], act.id]}
  end
end

app/helpers/activity_photos_helper.rb
module ActivityPhotosHelper
end

app/views/activity_photos/_form.html.erb
<%= form_for(@activity_photo) do |f| %>
  <% if @activity_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_photo.errors.count, "error") %> prohibited this activity_photo from being saved:</h2>

      <ul>
      <% @activity_photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :activity %><br />
    <%= f.select :activity_id, @activities %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :file %><br />
    <%= f.uploadcare_uploader_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activity_photos/edit.html.erb
<h1>Editing activity_photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity_photo %> |
<%= link_to 'Back', activity_photos_path %>

app/views/activity_photos/index.html.erb
<h1>Listing activity_photos</h1>

<table>
  <tr>
    <th>Title</th>
    <th>File</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activity_photos.each do |activity_photo| %>
  <tr>
    <td><%= activity_photo.title %></td>
    <td><%= activity_photo.file %></td>
    <td><%= link_to 'Show', activity_photo %></td>
    <td><%= link_to 'Edit', edit_activity_photo_path(activity_photo) %></td>
    <td><%= link_to 'Destroy', activity_photo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity photo', new_activity_photo_path %>

app/views/activity_photos/new.html.erb
<h1>New activity_photo</h1>

<%= render 'form' %>

<%= link_to 'Back', activity_photos_path %>

app/views/activity_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @activity_photo.title %>
</p>

<p>
  <b>File:</b>
  <%= image_tag @activity_photo.file.public_url %>
</p>


<%= link_to 'Edit', edit_activity_photo_path(@activity_photo) %> |
<%= link_to 'Back', activity_photos_path %>