config/routes.rb
Sputnik::Application.routes.draw do
  scope '(:locale)', locale: /en|ru/ do
    root :to => 'index#show_lists', as: 'show_lists'
    match 'activity_list/:id' => 'index#show_list', as: 'show_list'

    match 'activities' => 'index#show_activities', as: 'show_activities'
    match 'activity/:id' => 'index#show_activity', as: 'show_activity'
  end

  match '/admin' => 'admin#index', as: 'admin'
  scope '/admin' do
    resources :lists, :activities, :activity_photos
  end

end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id         :integer          not null, primary key
#  lead_text  :text
#  full_text  :text
#  features   :text
#  video      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string(255)
#

class Activity < ActiveRecord::Base
  attr_accessor :lists_params
  
  has_and_belongs_to_many :lists
  has_many :activity_photos

  accepts_nested_attributes_for :activity_photos, allow_destroy: true
  accepts_nested_attributes_for :lists

  attr_accessible :lead_text, :full_text, :features, :video, :list_id, :title, 
                  :activity_photos_attributes, :translations_attributes, :lists_params

  translates :lead_text, :full_text, :features, :title
  accepts_nested_attributes_for :translations

  def main_photo
    if self.activity_photos
      if self.activity_photos.where(is_main: true).present?
        self.activity_photos.where(is_main: true).first
      else
        self.activity_photos.first
      end
    else
      nil
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < AdminController
  before_filter :get_lists, only: [:new, :edit]
  after_filter :save_lists, only: [:create, :update]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: t('.activity_created') }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: t('.activity_updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end

private

  def get_lists
    @lists = List.all.map {|list| [list.title, list.id]}
  end

  def save_lists
    if params[:activity][:lists_params]
      activity = Activity.find(params[:id])

      params[:activity][:lists_params].each do |list_param|
        list = List.find(list_param[1][:id])
        activity.lists << list if !activity.lists.include?(list)
        if list_param[1][:_destroy] && list_param[1][:_destroy] == "1"
          activity.lists.destroy(list)
        end
      end
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_add_to_list.html.erb
<div class="list-box">
    <%= select_tag "activity[lists_params][uniq_id][id]", options_for_select(@lists), class: 'form-control input-sm' %>
</div>

app/views/activities/_form.html.erb
<%= form_for @activity, class: 'form' do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2>При попытке сохранить форму были ошибки:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="col-md-6">
    <div class="field form-group">
      <%= f.label 'Название (english)' %><br />
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="col-md-6">
    <%= f.globalize_fields_for :ru do |f_ru| %>
    <div class="field form-group">
      <%= f_ru.label 'Название (русский)' %><br />
      <%= f_ru.text_field :title, class: 'form-control' %>
      </div>
    <% end %>
  </div>  

  <div class="col-md-12">
    <div class="field form-group lists">
      <%= f.label 'В списках экскурсий' %><br />

      <div class="lists-box">
        <% if @activity.lists.present? %>
          <% for list in @activity.lists %>
            <%= fields_for 'activity[lists_params][]', list do |ff| %>
              <div class="list-box">
                <h4><%= link_to ff.object.title, list_path(ff.object) %> 
                    <%= link_to 'Удалить из списка', '#', class: 'btn btn-warning btn-xs btn-remove' %></h4>
                <%= ff.hidden_field :_destroy, class: "destroy" %>
                <%= ff.hidden_field :id %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <%= link_to 'Добавить в список', '#', 
                                       remote: true, 
                                       class: 'add-to-list-link btn btn-primary btn-xs', 
                                       data: { partial: render('add_to_list', f: f).gsub('\n','') } %>
    </div>
  </div>
  
  <div class="col-md-6">
    <div class="field form-group">
      <%= f.label 'Описание (english)' %><br />
      <%= f.text_area :lead_text, class: 'form-control' %>
    </div>
  </div>

  <div class="col-md-6">
    <%= f.globalize_fields_for :ru do |f_ru| %>
    <div class="field form-group">
      <%= f_ru.label 'Описание (русский)' %><br />
      <%= f_ru.text_area :lead_text, class: 'form-control' %>
    </div>
    <% end %>
  </div>

  <div class="col-md-6">
    <div class="field form-group">
      <%= f.label 'Полный текст (english)' %><br />
      <%= f.text_area :full_text, class: 'form-control' %>
    </div>
  </div>

  <div class="col-md-6">
    <%= f.globalize_fields_for :ru do |f_ru| %>
    <div class="field form-group">
      <%= f_ru.label 'Полный текст (русский)' %><br />
      <%= f_ru.text_area :full_text, class: 'form-control' %>
    </div>
    <% end %>
  </div>

  <div class="col-md-6">
    <div class="field form-group">
      <%= f.label 'Особенности экскурсии (english)' %><br />
      <%= f.text_area :features, class: 'form-control' %>
    </div>
  </div>

  <div class="col-md-6">
    <%= f.globalize_fields_for :ru do |f_ru| %>
    <div class="field form-group">
      <%= f_ru.label 'Особенности экскурсии (русский)' %><br />
      <%= f_ru.text_area :features, class: 'form-control' %>
    </div>
    <% end %>
  </div>
    
  <div class="col-md-12">
    <div class="field form-group">
      <%= f.label 'ID видео на вимео' %><br />
      <%= f.text_field :video, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group photos col-md-12">
    <%= f.label 'Фотографии' %><br />
    
    <div class="photos-box">
      <%= f.fields_for :activity_photos do |ff| %>
        <div class="ucare-box well well-sm">
          <%= ff.hidden_field :_destroy, class: 'destroy' %>
          <%= ff.uploadcare_uploader_field :file %>
          Является обложкой: <%= ff.check_box :is_main, class: 'is-main-checkbox' %>
        </div>
      <% end %>
    </div>
    
    <br>
    <%= link_to 'Добавить фотографию', '#', 
                                       remote: true, 
                                       class: 'add-photo-link btn btn-primary btn-xs', 
                                       data: { partial: render('new_photo', f: f).gsub('\n','') } %>
  </div>

  <div class="actions col-md-12">
    <%= f.submit 'Сохранить экскурсию', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/activities/_new_photo.html.erb
<%= f.fields_for :activity_photos, @activity.activity_photos.new do |ff| %>
    <div class="ucare-box well well-sm">
        <%= ff.uploadcare_uploader_field :file %>
        Является обложкой: <%= ff.check_box :is_main, class: 'is-main-checkbox' %>
    </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Редактировать экскурсию</h1>

<%= render 'form' %>

<div class="col-md-12">
    <br>
    <%= link_to 'Показать', @activity %> |
    <%= link_to 'Назад', activities_path %>
</div>

app/views/activities/index.html.erb
<h1>Экскурсии</h1>

<table class="table">
  <tr>
    <th>Название</th>
    <th>Описание</th>
    <th>Полный текст</th>
    <th>Особенности экскурсии</th>
    <th>ID видео на вимео</th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= link_to activity.title, activity %></td>
    <td><%= activity.lead_text[0..15] %></td>
    <td><%= activity.full_text[0..15] %></td>
    <td><%= activity.features[0..15] %></td>
    <td><%= activity.video %></td>
    <td><%= link_to 'Редактировать', edit_activity_path(activity) %></td>
    <td><%= link_to 'Удалить', activity, confirm: 'Точно удалить?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Добавить экскурсию', new_activity_path, class: 'btn btn-primary' %>

app/views/activities/new.html.erb
<h1>Новая экскурсия</h1>

<%= render 'form' %>

<div class="col-md-12">
    <br>
    <%= link_to 'Back', activities_path %>
</div>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Название:</b>
  <div><%= @activity.title %></div>
</p>

<p>
  <b>Описание:</b>
  <div><%= @activity.lead_text %></div>
</p>

<p>
  <b>Полный текст:</b>
  <div><%= @activity.full_text %></div>
</p>

<p>
  <b>Особенности экскурсии:</b>
  <div><%= @activity.features %></div>
</p>

<p>
  <b>ID видео на вимео</b>
  <div><%= @activity.video %></div>
</p>


<%= link_to 'Редактировать экскурсию', edit_activity_path(@activity) %> |
<%= link_to 'Назад', activities_path %>