config/routes.rb
Sputnik::Application.routes.draw do
  scope '(:locale)', locale: /en|ru/ do
    root :to => 'index#show_lists', as: 'show_lists'
    match 'activity_list/:id' => 'index#show_list', as: 'show_list'

    match 'activities' => 'index#show_activities', as: 'show_activities'
    match 'activity/:id' => 'index#show_activity', as: 'show_activity'
  end

  match '/admin' => 'admin#index', as: 'admin'
  scope '/admin' do
    resources :lists, :activities, :activity_photos
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sputnik Admin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= uploadcare_include_tag %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
        <div class="navbar navbar-default">
            <div class="navbar-header">
                <%= link_to 'Sputnik Admin', admin_path, class: 'navbar-brand' %>
            </div>
            
            <div class="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><%= link_to 'Списки экскурсий', lists_path %></li>
                    <li><%= link_to 'Экскурсии', activities_path %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><%= link_to 'На сайт', show_lists_path %></li>
              </ul>
            </div>
        </div>

        <%= yield %>
    </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sputnik</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
        <div class="navbar navbar-default">
            <div class="navbar-header">
                <%= link_to 'Sputnik', show_lists_path, class: 'navbar-brand' %>
            </div>
            
            <div class="navbar-collapse">
              <ul class="nav navbar-nav">
                  <li><%= link_to t('.lists'), show_lists_path %></li>
                  <li><%= link_to t('.activities'), show_activities_path %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                  <li><%= link_to 'En', locale: 'en' %></li>
                  <li><%= link_to 'Ru', locale: 'ru' %></li>
              </ul>
            </div>
        </div>

        <%= yield %>
    </div>
</body>
</html>